export const mockDB = {
    auth_users: [
        // Usuarios originales
        { user: "22370703", pass: "123", role: "alumno", refId: 1 },
        { user: "22370533", pass: "123", role: "alumno", refId: 8 },
        { user: "23370112", pass: "123", role: "alumno", refId: 2 },
        { user: "21370998", pass: "123", role: "alumno", refId: 4 },
        { user: "24370555", pass: "123", role: "alumno", refId: 3 },
        { user: "25370001", pass: "123", role: "alumno", refId: 5 },
        { user: "22370111", pass: "123", role: "alumno", refId: 7 },
        { user: "22370888", pass: "123", role: "alumno", refId: 9 },
        { user: "22370999", pass: "123", role: "alumno", refId: 10 },
        // Nuevos alumnos (11-27)
        { user: "22370110", pass: "123", role: "alumno", refId: 11 },
        { user: "22370112", pass: "123", role: "alumno", refId: 12 },
        { user: "22370113", pass: "123", role: "alumno", refId: 13 },
        { user: "22370114", pass: "123", role: "alumno", refId: 14 },
        { user: "22370115", pass: "123", role: "alumno", refId: 15 },
        { user: "22370116", pass: "123", role: "alumno", refId: 16 },
        { user: "22370117", pass: "123", role: "alumno", refId: 17 },
        { user: "22370118", pass: "123", role: "alumno", refId: 18 },
        { user: "22370119", pass: "123", role: "alumno", refId: 19 },
        { user: "22370120", pass: "123", role: "alumno", refId: 20 },
        { user: "22370121", pass: "123", role: "alumno", refId: 21 },
        { user: "22370122", pass: "123", role: "alumno", refId: 22 },
        { user: "22370123", pass: "123", role: "alumno", refId: 23 },
        { user: "22370124", pass: "123", role: "alumno", refId: 24 },
        { user: "22370125", pass: "123", role: "alumno", refId: 25 },
        { user: "22370126", pass: "123", role: "alumno", refId: 26 },
        { user: "22370127", pass: "123", role: "alumno", refId: 27 },
        { user: "23370753", pass: "123", role: "alumno", refId: 28 },

        // Tutores
        { user: "aliciacortes", pass: "123", role: "tutor", refId: 1 },
        { user: "elenaruiz", pass: "123", role: "tutor", refId: 2 },
        { user: "teresan", pass: "123", role: "tutor", refId: 3 },

        { user: "eval_basquet", pass: "123", role: "encargado", idActividad: "E2" },
        { user: "admin", pass: "123", role: "admin" }
    ],

    actividades_catalogo: [
        { id: "A1", nombre: "Taller de Lectura Avanzada", tipo: "Académica", cupo_max: 30, ocupados: 28 },
        { id: "A2", nombre: "Bootcamp Python & IA", tipo: "Académica", cupo_max: 20, ocupados: 20 },
        { id: "A3", nombre: "Redacción Científica", tipo: "Académica", cupo_max: 15, ocupados: 5 },
        { id: "E1", nombre: "Torneo de Ajedrez Institucional", tipo: "Extraescolar", cupo_max: 40, ocupados: 12 },
        { id: "E2", nombre: "Selección de Básquetbol", tipo: "Extraescolar", cupo_max: 15, ocupados: 14 }
    ],

    tutores: [
        {
            id: 1,
            nombre: "Mtra. Alicia Cortés Fernández",
            numero_empleado: "T-1001",
            horario_atencion: "Lunes a Jueves 07:00 - 12:00",
            area: "Tutorías Académicas / Ingeniería en Tecnologías de la Información"
        },
        {
            id: 2,
            nombre: "Dra. Elena Ruiz",
            numero_empleado: "T-1002",
            horario_atencion: "Martes y Jueves 09:00 - 13:00",
            area: "Departamento de Ciencias Básicas"
        },
        {
            id: 3,
            nombre: "Lic. Teresa N",
            numero_empleado: "T-1003",
            horario_atencion: "Lunes, Miércoles 11:00 - 15:00",
            area: "Tutorías Académicas / Desarrollo Estudiantil"
        }
    ],

    alumnos: [
        {
            id: 1,
            nombre: "CHRISTOPHER ELIHU ALVAREZ RODRIGUEZ",
            matricula: "22370703",
            carrera: "ING. TEC. INF. COM",
            semestre: 8,
            prom_sin_rep: 91.0,
            estatus: "VIGENTE",
            tutorId: 1,
            liberado: false,
            evidencias: [],
            historial_actividades: [
                { id_actividad: "A1", nombre: "Rondalla", tipo: "Académica", estado: "Suficiente" },
                { id_actividad: "A2", nombre: "Fort. Fis.", tipo: "Académica", estado: "Suficiente" },
                { id_actividad: "E1", nombre: "ENAC", tipo: "Extraescolar", estado: "Excelente" },
                { id_actividad: "E2", nombre: "Circulo de Lectura", tipo: "Extraescolar", estado: "Notable" }
            ],
            actividad_actual: null
        },
        {
            id: 2,
            nombre: "MARIA FERNANDA LOPEZ PEREZ",
            matricula: "23370112",
            carrera: "ING. INDUSTRIAL",
            semestre: 5,
            prom_sin_rep: 85.5,
            estatus: "VIGENTE",
            tutorId: 1,
            liberado: false,
            evidencias: [],
            historial_actividades: [
                { id_actividad: "A1", nombre: "Taller Lectura", tipo: "Académica", estado: "Suficiente" },
                { id_actividad: "E1", nombre: "Ajedrez", tipo: "Extraescolar", estado: "Insuficiente" }
            ],
            actividad_actual: { id_actividad: "E2", nombre: "Selección de Básquetbol", tipo: "Extraescolar" }
        },
        {
            id: 3,
            nombre: "PEDRO ANTONIO RAMIREZ SOTO",
            matricula: "24370555",
            carrera: "ING. ELECTROMECÁNICA",
            semestre: 3,
            prom_sin_rep: 92.0,
            estatus: "VIGENTE",
            tutorId: 1,
            liberado: false,
            evidencias: [],
            historial_actividades: [
                { id_actividad: "E3", nombre: "Banda de Guerra", tipo: "Extraescolar", estado: "Excelente" }
            ],
            actividad_actual: null
        },
        {
            id: 4,
            nombre: "JUAN CARLOS HERNANDEZ DIAZ",
            matricula: "21370998",
            carrera: "ING. MECATRÓNICA",
            semestre: 6,
            prom_sin_rep: 70.0,
            estatus: "BAJA TEMPORAL",
            tutorId: 2,
            liberado: false,
            evidencias: [],
            historial_actividades: [
                { id_actividad: "A2", nombre: "Bootcamp Python", tipo: "Académica", estado: "Insuficiente" }
            ],
            actividad_actual: null
        },
        {
            id: 5,
            nombre: "ANA SOFIA MARTINEZ RUIZ",
            matricula: "25370001",
            carrera: "ING. GESTIÓN EMPRESARIAL",
            semestre: 1,
            prom_sin_rep: 98.0,
            estatus: "VIGENTE",
            tutorId: 1,
            liberado: false,
            evidencias: [],
            historial_actividades: [],
            actividad_actual: null
        },
        {
            id: 6,
            nombre: "LUIS ENRIQUE GOMEZ VEGA",
            matricula: "20371122",
            carrera: "ING. SISTEMAS",
            semestre: 9,
            prom_sin_rep: 88.0,
            estatus: "VIGENTE",
            tutorId: 1,
            liberado: true,
            evidencias: [],
            historial_actividades: [
                { id_actividad: "A1", nombre: "Taller", tipo: "Académica", estado: "Suficiente" },
                { id_actividad: "A2", nombre: "Python", tipo: "Académica", estado: "Notable" },
                { id_actividad: "E1", nombre: "Ajedrez", tipo: "Extraescolar", estado: "Excelente" },
                { id_actividad: "E4", nombre: "Teatro", tipo: "Extraescolar", estado: "Notable" },
                { id_actividad: "LIB_OFICIAL", nombre: "Tutorías", tipo: "Acreditación Institucional", estado: "Liberado" }
            ],
            actividad_actual: null
        },
        {
            id: 7,
            nombre: "CARMEN ORTIZ MENDOZA",
            matricula: "22370111",
            carrera: "ING. TEC. INF. COM",
            semestre: 8,
            prom_sin_rep: 95.0,
            estatus: "VIGENTE",
            tutorId: 1,
            liberado: false,
            evidencias: [],
            historial_actividades: [
                { id_actividad: "A2", nombre: "Python", tipo: "Académica", estado: "Excelente" },
                { id_actividad: "A4", nombre: "Robótica", tipo: "Académica", estado: "Excelente" },
                { id_actividad: "E1", nombre: "Ajedrez", tipo: "Extraescolar", estado: "Excelente" },
                { id_actividad: "E3", nombre: "Banda Guerra", tipo: "Extraescolar", estado: "Excelente" }
            ],
            actividad_actual: null
        },
        {
            id: 8,
            nombre: "FATIMA GONZALEZ CORONA",
            matricula: "22370533",
            carrera: "ING. MECATRONICA",
            semestre: 8,
            prom_sin_rep: 87.0,
            estatus: "VIGENTE",
            tutorId: 3,
            liberado: false,
            evidencias: [],
            historial_actividades: [
                { id_actividad: "Z1", nombre: "Escolta y Banda de guerra.", tipo: "Académica", estado: "Excelente" },
                { id_actividad: "Z2", nombre: "Futbol", tipo: "Extraescolar", estado: "Excelente" }
            ],
            actividad_actual: null
        },
        {
            id: 9,
            nombre: "RICARDO TAPIA VARGAS",
            matricula: "22370888",
            carrera: "ING. TEC. INF. COM",
            semestre: 4,
            prom_sin_rep: 82.3,
            estatus: "VIGENTE",
            tutorId: 2,
            liberado: false,
            evidencias: [],
            historial_actividades: [{ id_actividad: "A4", nombre: "IoT", tipo: "Académica", estado: "Suficiente" }],
            actividad_actual: null
        },
        {
            id: 10,
            nombre: "VALERIA JIMENEZ CASTRO",
            matricula: "22370999",
            carrera: "ING. INDUSTRIAL",
            semestre: 6,
            prom_sin_rep: 89.9,
            estatus: "VIGENTE",
            tutorId: 3,
            liberado: false,
            evidencias: [],
            historial_actividades: [{ id_actividad: "E3", nombre: "Fútbol Femenil", tipo: "Extraescolar", estado: "Notable" }],
            actividad_actual: null
        },
        {
            id: 11,
            nombre: "SERGIO ACOSTA MEZA",
            matricula: "22370110",
            carrera: "ING. SISTEMAS",
            semestre: 4,
            prom_sin_rep: 84.0,
            estatus: "VIGENTE",
            tutorId: 2,
            liberado: false,
            evidencias: [],
            historial_actividades: [],
            actividad_actual: null
        },
        {
            id: 12,
            nombre: "DIANA LAURA REYES",
            matricula: "22370112",
            carrera: "ING. INDUSTRIAL",
            semestre: 2,
            prom_sin_rep: 93.5,
            estatus: "VIGENTE",
            tutorId: 1,
            liberado: false,
            evidencias: [],
            historial_actividades: [],
            actividad_actual: null
        },
        {
            id: 13,
            nombre: "ROBERTO CARLOS MONTIEL",
            matricula: "22370113",
            carrera: "ING. ELECTRICA",
            semestre: 7,
            prom_sin_rep: 78.2,
            estatus: "VIGENTE",
            tutorId: 3,
            liberado: false,
            evidencias: [],
            historial_actividades: [],
            actividad_actual: null
        },
        {
            id: 14,
            nombre: "GABRIELA SOSA LUNA",
            matricula: "22370114",
            carrera: "ING. TEC. INF. COM",
            semestre: 5,
            prom_sin_rep: 88.9,
            estatus: "VIGENTE",
            tutorId: 1,
            liberado: false,
            evidencias: [],
            historial_actividades: [],
            actividad_actual: null
        },
        {
            id: 15,
            nombre: "ALEJANDRO NAVA DIAZ",
            matricula: "22370115",
            carrera: "ING. MECATRONICA",
            semestre: 3,
            prom_sin_rep: 81.0,
            estatus: "VIGENTE",
            tutorId: 2,
            liberado: false,
            evidencias: [],
            historial_actividades: [],
            actividad_actual: null
        },
        {
            id: 16,
            nombre: "MONICA RUIZ ESPARZA",
            matricula: "22370116",
            carrera: "ING. INDUSTRIAL",
            semestre: 8,
            prom_sin_rep: 95.1,
            estatus: "VIGENTE",
            tutorId: 3,
            liberado: false,
            evidencias: [],
            historial_actividades: [],
            actividad_actual: null
        },
        {
            id: 17,
            nombre: "FERNANDO TORRES CANO",
            matricula: "22370117",
            carrera: "ING. SISTEMAS",
            semestre: 6,
            prom_sin_rep: 87.4,
            estatus: "VIGENTE",
            tutorId: 1,
            liberado: false,
            evidencias: [],
            historial_actividades: [],
            actividad_actual: null
        },
        {
            id: 18,
            nombre: "BEATRIZ ADRIANA SOLIS",
            matricula: "22370118",
            carrera: "ING. GESTION EMP.",
            semestre: 4,
            prom_sin_rep: 90.0,
            estatus: "VIGENTE",
            tutorId: 2,
            liberado: false,
            evidencias: [],
            historial_actividades: [],
            actividad_actual: null
        },
        {
            id: 19,
            nombre: "HUGO ENRIQUE MORALES",
            matricula: "22370119",
            carrera: "ING. ELECTRICA",
            semestre: 2,
            prom_sin_rep: 82.5,
            estatus: "VIGENTE",
            tutorId: 3,
            liberado: false,
            evidencias: [],
            historial_actividades: [],
            actividad_actual: null
        },
        {
            id: 20,
            nombre: "KARLA VANESSA LOPEZ",
            matricula: "22370120",
            carrera: "ING. TEC. INF. COM",
            semestre: 7,
            prom_sin_rep: 86.3,
            estatus: "VIGENTE",
            tutorId: 1,
            liberado: false,
            evidencias: [],
            historial_actividades: [],
            actividad_actual: null
        },
        {
            id: 21,
            nombre: "DANIEL ISAAC ROMERO",
            matricula: "22370121",
            carrera: "ING. MECATRONICA",
            semestre: 5,
            prom_sin_rep: 89.2,
            estatus: "VIGENTE",
            tutorId: 2,
            liberado: false,
            evidencias: [],
            historial_actividades: [],
            actividad_actual: null
        },
        {
            id: 22,
            nombre: "PATRICIA LUNA FLORES",
            matricula: "22370122",
            carrera: "ING. INDUSTRIAL",
            semestre: 3,
            prom_sin_rep: 94.7,
            estatus: "VIGENTE",
            tutorId: 3,
            liberado: false,
            evidencias: [],
            historial_actividades: [],
            actividad_actual: null
        },
        {
            id: 23,
            nombre: "JORGE LUIS SALAZAR",
            matricula: "22370123",
            carrera: "ING. SISTEMAS",
            semestre: 9,
            prom_sin_rep: 80.5,
            estatus: "VIGENTE",
            tutorId: 1,
            liberado: false,
            evidencias: [],
            historial_actividades: [],
            actividad_actual: null
        },
        {
            id: 24,
            nombre: "ELENA MARGARITA ORTIZ",
            matricula: "22370124",
            carrera: "ING. GESTION EMP.",
            semestre: 6,
            prom_sin_rep: 91.8,
            estatus: "VIGENTE",
            tutorId: 2,
            liberado: false,
            evidencias: [],
            historial_actividades: [],
            actividad_actual: null
        },
        {
            id: 25,
            nombre: "RAUL ARMANDO GOMEZ",
            matricula: "22370125",
            carrera: "ING. ELECTRICA",
            semestre: 4,
            prom_sin_rep: 83.4,
            estatus: "VIGENTE",
            tutorId: 3,
            liberado: false,
            evidencias: [],
            historial_actividades: [],
            actividad_actual: null
        },
        {
            id: 26,
            nombre: "LORENA ISABEL CASTRO",
            matricula: "22370126",
            carrera: "ING. TEC. INF. COM",
            semestre: 2,
            prom_sin_rep: 88.0,
            estatus: "VIGENTE",
            tutorId: 1,
            liberado: false,
            evidencias: [],
            historial_actividades: [],
            actividad_actual: null
        },
        {
            id: 27,
            nombre: "OSCAR EDUARDO MEZA",
            matricula: "22370127",
            carrera: "ING. MECATRONICA",
            semestre: 7,
            prom_sin_rep: 85.0,
            estatus: "VIGENTE",
            tutorId: 2,
            liberado: false,
            evidencias: [],
            historial_actividades: [],
            actividad_actual: null
        },
        {
            id: 28,
            nombre: "DANIEL MENDOZA PARRA",
            matricula: "23370753",
            carrera: "ING. TEC. INF. COM",
            semestre: 8,
            prom_sin_rep: 90.29,
            estatus: "VIGENTE",
            tutorId: 1,
            liberado: false,
            evidencias: [],
            historial_actividades: [
                { id_actividad: "A1", nombre: "Taller Lectura", tipo: "Académica", estado: "Suficiente" },
                { id_actividad: "E1", nombre: "Atletismo", tipo: "Extraescolar", estado: "Suficiente" },
                { id_actividad: "E2", nombre: "ENAC", tipo: "Académica", estado: "Excelente" }
            ],
            actividad_actual: { id_actividad: "E2", nombre: "Selección de Básquetbol", tipo: "Extraescolar" }
        },
        
    ]
};
